# Generated by Django 2.0.7 on 2018-07-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes_posts',
            field=models.ManyToManyField(blank=True, related_name='like_posts', related_query_name='like_posts', to='posts.Post'),
        ),
    ]
