# Generated by Django 2.1 on 2018-08-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180802_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
