# Generated by Django 2.0.7 on 2018-07-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180730_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('C', 'Customer'), ('H', 'Host')], default='C', max_length=1),
        ),
    ]
