# Generated by Django 2.1 on 2018-08-03 04:23

from django.db import migrations
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180801_2237'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', members.models.UserManager()),
            ],
        ),
    ]
