# Generated by Django 2.1 on 2018-08-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
