# Generated by Django 2.1 on 2018-08-20 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservation',
            name='reserved',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='예약된 날짜'),
            preserve_default=False,
        ),
    ]
