# Generated by Django 2.1 on 2018-08-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='rooms_cover_image',
            field=models.ImageField(max_length=255, upload_to='cover_image', verbose_name='숙소의 커버 이미지입니다.'),
        ),
    ]
