# Generated by Django 2.1 on 2018-08-11 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='rooms_cover_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='cover_image', verbose_name='숙소의 커버 이미지입니다.'),
            preserve_default=False,
        ),
    ]
