# Generated by Django 2.1 on 2018-08-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20180816_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='rooms_description',
            field=models.TextField(help_text='당신의 숙소를 소개하세요, 게스트의 흥미를 유발하는것이 중요합니다.', max_length=255, verbose_name='숙소 개요'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='rooms_tag',
            field=models.CharField(blank=True, help_text='검색에 사용될 지역 태그를 입력하세요', max_length=150, verbose_name='태그'),
        ),
    ]
