# Generated by Django 2.1 on 2018-08-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20180814_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='도시'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='address_country',
            field=models.CharField(blank=True, max_length=50, verbose_name='국가'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='rooms_name',
            field=models.CharField(help_text='숙소의 이름을 입력하세요', max_length=150, verbose_name='숙소 이름'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='rooms_tag',
            field=models.CharField(blank=True, help_text='검색에 사용될 지역 태그를 입력하세요', max_length=100, verbose_name='태그'),
        ),
    ]
