# Generated by Django 2.1 on 2018-08-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20180806_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='address_city',
            field=models.CharField(blank=True, max_length=50, verbose_name='도시'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='address_country',
            field=models.CharField(blank=True, max_length=30, verbose_name='국가'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='address_detail',
            field=models.CharField(blank=True, max_length=150, verbose_name='상세 주소'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='address_district',
            field=models.CharField(blank=True, max_length=150, verbose_name='시/군/구'),
        ),
    ]
