# Generated by Django 2.0.7 on 2018-08-01 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomdetail_rooms_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetail',
            name='rooms_name',
        ),
    ]
