# Generated by Django 2.1 on 2018-08-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rooms_rooms_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='room_image',
            field=models.ImageField(upload_to='room_profile_image', verbose_name='숙소 프로필 이미지를 업로드 해주세요'),
        ),
    ]
