# Generated by Django 2.1 on 2018-08-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20180820_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationReserved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='roomreservation',
            name='reserved',
        ),
        migrations.AddField(
            model_name='reservationreserved',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_set', to='rooms.RoomReservation'),
        ),
    ]
