# Generated by Django 2.1 on 2018-08-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20180814_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
