# Generated by Django 2.1 on 2018-08-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20180814_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='address_latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, verbose_name='Google MAP API 위도'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='address_longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, verbose_name='Google MAP API 경도'),
        ),
    ]
