# Generated by Django 2.1 on 2018-08-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20180815_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
