# Generated by Django 2.1 on 2018-08-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20180815_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomreservation',
            options={'ordering': ['-created_at']},
        ),
    ]
