# Generated by Django 2.1 on 2018-08-21 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20180821_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationreserved',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_disable', to='rooms.Rooms'),
        ),
    ]
