# Generated by Django 2.1 on 2018-08-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20180821_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationreserved',
            old_name='reservation',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='reservationreserved',
            name='reservations',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
