# Generated by Django 2.1 on 2018-08-21 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20180821_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationreserved',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_disable', to='rooms.RoomReservation'),
        ),
    ]
