# Generated by Django 2.1 on 2018-08-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20180821_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationreserved',
            name='reservations',
            field=models.DateField(blank=True, null=True),
        ),
    ]
